spring:
  jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: com.shj.pms.pmspassport.config.CustomSpringPhysicalNamingStrategy
  properties:
    hibernate:
      format_sql: true
      show_sql: true
  datasource:
    url: jdbc:mysql://118.25.157.226:3306/pms-dev?autoreconnect=true&useSSL=false
    username: "root"
    password: "123456"
    druid:
      url: jdbc:mysql://118.25.157.226:3306/pms-dev?autoreconnect=true&useSSL=false
      username: "root"
      password: "123456"
      driver-class-name:  com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: stat,slf4j

jwt:
  expiration: 7500000
  token: Authorization
